services:
  postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autodrive_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/autodrive_db
      JWT_SECRET: Autoescuela2026JWTScecret
      TASA_DGT_CONCEPTO_PATTERN: Tasa DGT (Tasa 2.1)
      TASA_DGT_MAX_SUSPENSOS: 2
      TASA_DGT_IMPORTE_DEFAULT: 94.05
      RENOVACION_DIAS_ESPERA_DEFAULT: 0
      RENOVACION_CLASES_OBLIGATORIAS_DEFAULT: 0
      RENOVACION_DIAS_ESPERA_A1: 7
      RENOVACION_CLASES_OBLIGATORIAS_A1: 2
      RENOVACION_DIAS_ESPERA_A2: 10
      RENOVACION_CLASES_OBLIGATORIAS_A2: 3
      RENOVACION_DIAS_ESPERA_A: 7
      RENOVACION_CLASES_OBLIGATORIAS_A: 2
      RENOVACION_DIAS_ESPERA_B: 15
      RENOVACION_CLASES_OBLIGATORIAS_B: 3
      RENOVACION_DIAS_ESPERA_C: 21
      RENOVACION_CLASES_OBLIGATORIAS_C: 4
      RENOVACION_DIAS_ESPERA_D: 21
      RENOVACION_CLASES_OBLIGATORIAS_D: 5
      RENOVACION_DIAS_ESPERA_E: 14
      RENOVACION_CLASES_OBLIGATORIAS_E: 3

    volumes:
      - ./backend/uploads:/app/uploads

    depends_on:
      - postgres

volumes:
  postgres_data:
